id: I77A4C883
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:13:36+00:00'
last_modified: '2022-06-07T18:09:19.990764+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27416
  title: ཁྲི་ཚོགས་ཚུལ་ཁྲིམས་རྣམ་པར་དག་པའི་གླིང་གི་མཁན་བརྒྱུད་རྣམ་ཐར་དད་པའི་རྒྱན་མཆོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CD30:
      image_group_id: I4323
      title: ''
      total_pages: 126
      order: 1
      base_file: CD30.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
