id: P003184
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:45:51.311533
source_metadata:
  id: bdr:W27416
  title: ཁྲི་ཚོགས་ཚུལ་ཁྲིམས་རྣམ་པར་དག་པའི་གླིང་གི་མཁན་བརྒྱུད་རྣམ་ཐར་དད་པའི་རྒྱན་མཆོག
  author: ''
  volumes:
    9db9e03529bd4da1b7896ed3469e5bc7:
      image_group_id: I4323
      title: ''
      volume_number: 1
      total_pages: 126
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
